application: puzzlegame
version: 1
runtime: go 
api_version: go1 

handlers: 
- url: /(.*\.(jpg|gif|png|css|html|js|go))
  static_files: \1
  upload: (.*\.(jpg|gif|png|css|html|js))

- url: /.*
  script: _go_app


- url: /js
  static_dir: \js

- url: /bootstrap
  static_dir: \bootstrap

- url: /bootstrap/css
  static_dir: \bootstrap\css

- url: /bootstrap/js
  static_dir: \bootstrap\js

- url: /bootstrap/fonts
  static_dir: \bootstrap\fonts


- url: /PuzzleGame.html
  static_files: \PuzzleGame.html
  upload: \PuzzleGame.html
  login: required


- url: /SignUp.html
  static_files: \SignUp.html
  upload: \SignUp.html

- url: /LogIn.html
  static_files: \LogIn.html
  upload: \LogIn.html

- url: /updateScore
  script: _go_app

- url: /getPuzzle
  script: HelloStuff.go

- url: /uploadForm
  script: HelloStuff.go

- url: /upload
  script: HelloStuff.go

- url: /uploadPuzzle
  script: HelloStuff.go

- url: /login
  script: HelloStuff.go
  login: required

- url: /getSavePuzzle
  script: HelloStuff.go

- url: /getSavedGames
  script: HelloStuff.go
  
- url: /saveMove
  script: HelloStuff.go

- url: /deleteMoves
  script: HelloStuff.go
  
- url: /saveMoves
  script: HelloStuff.go

- url: /logout
  script: HelloStuff.go

- url: /createGame
  script: HelloStuff.go

- url: /getSavedMoves
  script: HelloStuff.go